export const STATES = Object.freeze({
  RECEIVED: 'RECEIVED',
  BASELINE_PASSED: 'BASELINE_PASSED',
  REPRODUCING: 'REPRODUCING',
  REPRODUCED: 'REPRODUCED',
  PATCHING: 'PATCHING',
  VERIFYING: 'VERIFYING',
  VERIFIED: 'VERIFIED',
  WAITING_PUBLISH_APPROVAL: 'WAITING_PUBLISH_APPROVAL',
  APPROVAL_DENIED: 'APPROVAL_DENIED',
  PUBLISHING: 'PUBLISHING',
  PR_CREATED: 'PR_CREATED',
  NEEDS_INFO: 'NEEDS_INFO',
  OUT_OF_SCOPE: 'OUT_OF_SCOPE',
  ENVIRONMENT_ERROR: 'ENVIRONMENT_ERROR',
  POLICY_REJECTED: 'POLICY_REJECTED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  PUBLISH_FAILED: 'PUBLISH_FAILED'
});

export const TERMINAL_STATES = new Set([
  STATES.PR_CREATED, STATES.NEEDS_INFO, STATES.OUT_OF_SCOPE,
  STATES.ENVIRONMENT_ERROR, STATES.POLICY_REJECTED,
  STATES.VERIFICATION_FAILED, STATES.PUBLISH_FAILED, STATES.APPROVAL_DENIED
]);

export const TRANSITIONS = Object.freeze({
  RECEIVED: ['BASELINE_PASSED', 'OUT_OF_SCOPE', 'ENVIRONMENT_ERROR', 'POLICY_REJECTED'],
  BASELINE_PASSED: ['REPRODUCING'],
  REPRODUCING: ['REPRODUCED', 'NEEDS_INFO', 'ENVIRONMENT_ERROR', 'POLICY_REJECTED'],
  REPRODUCED: ['PATCHING'],
  PATCHING: ['VERIFYING', 'POLICY_REJECTED'],
  VERIFYING: ['VERIFIED', 'VERIFICATION_FAILED', 'ENVIRONMENT_ERROR', 'POLICY_REJECTED'],
  VERIFIED: ['WAITING_PUBLISH_APPROVAL', 'PUBLISHING'],
  WAITING_PUBLISH_APPROVAL: ['PUBLISHING', 'APPROVAL_DENIED', 'VERIFICATION_FAILED'],
  PUBLISHING: ['PR_CREATED', 'PUBLISH_FAILED', 'VERIFICATION_FAILED']
});

export const DEFAULT_POLICY = Object.freeze({
  repository: 'abhiraj75/kora-store',
  targetBranch: 'main',
  requiredLabel: 'redhanded',
  allowedApplicationPaths: ['src/cart.js'],
  reproductionPrefix: 'repro/issue-',
  maxChangedLines: 30,
  maxAttempts: 2,
  evidenceModes: ['tests-only', 'visual']
});
